### ISSUE TITLE
Issue on Windows use

### ISSUE THREAD

**Issue by Halley73** [profesorfalken/jProcesses#14]
Hi,
i'm trying to use this library to make some controls on processes.

Under Linux all works fine but when i run my program in Windows i receive the error in attachment.

[JProcesses_Error.txt](https://github.com/profesorfalken/jProcesses/files/350165/JProcesses_Error.txt)

Regards

**Comment by profesorfalken** [comment]
Hello.

Yes, it is my fault. 

I guess you are not using Maven. In that case you should add manually into your classpath the dependency to WMI4Java. 

You can found the jar here: https://repo1.maven.org/maven2/com/profesorfalken/WMI4Java/1.4.2/WMI4Java-1.4.2.jar

Tell me if it works.

**Comment by Halley73** [comment]
Ok, thank you, I've added WMI and now it works.

Second link -jar-with-dependencies give me a 404 error.

Regards

**Comment by profesorfalken** [comment]
Cool. Thanks for reporting the wrong link. 

Here you are the good one if you are interested: 

https://github.com/profesorfalken/profesorfalken.github.io/blob/master/files/jProcesses-1.6.1-jar-with-dependencies.jar?raw=true
