### ISSUE TITLE
mac compatibility

### ISSUE THREAD

**Issue by jkuharev** [profesorfalken/jProcesses#3]
there are multiple problems regarding usage of ps

# Problem #1 

For retrieving advanced information from ps-utility, you have changed UnixProcessesService.PS_COLUMNS to "pid,ruser,vsize,rssize,%cpu,bsdstart,bsdtime,nice,comm,cmd".
This is fine for any Linux but fails (at least partially) on some other UNIX machines.
e.g. on a Max OS X 10.11.3
----
ps -e -o pid,ruser,vsize,rssize,%cpu,bsdstart,bsdtime,nice,comm,cmd
ps: rssize: keyword not found
ps: bsdstart: keyword not found
ps: bsdtime: keyword not found
ps: cmd: keyword not found
----
see BSD man pages (http://www.freebsd.org/cgi/man.cgi?query=ps&apropos=0&sektion=0&manpath=FreeBSD+2.2.5-RELEASE&format=html).

I suggest to use "pid,ruser,vsize,rss,%cpu,start,cputime,nice,comm,command"
which I have successfully tested both on Mac and Linux.
--------------

# Problem #2 
getProcessesData(String name) uses "ps -C whatever",
which is very Linux specific and also does not work for BSD (see man pages).
One possibility is to use grep or pgrep. 
At the other hand we can list all processes and look for the process name in Java.

**Comment by profesorfalken** [comment]
Thanks for your useful feedback, jkuharev. I wil check it tonight.

**Comment by profesorfalken** [comment]
The first work perfectly with the proposed solution. 

However the second... I try to make a grep but to call the command from java I have to do something like: "bash", "-c", "ps o comm,pid,ruser,vsize,rss,%cpu,start,cputime,nice,command -e | grep "^java[[:blank:]]"" });

I wonder if the bash shell works out of the box in freebsd/Mac...

**Comment by profesorfalken** [comment]
Well this solution pass the tests in linux. I am going to push it. Could you check if it solves the problem on Mac?

**Comment by profesorfalken** [comment]
I close this issue since the conversation continued here: 

https://github.com/profesorfalken/jProcesses/pull/4
